# Generated by Django 6.0 on 2026-03-17 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_username_personface_recognitionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personface',
            name='camera_account',
        ),
        migrations.AddField(
            model_name='personface',
            name='allowed_cameras',
            field=models.ManyToManyField(blank=True, related_name='faces', to=settings.AUTH_USER_MODEL),
        ),
    ]
