# Generated by Django 6.0 on 2026-03-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_personface_camera_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_camera',
            field=models.BooleanField(default=False, verbose_name='Это устройство-камера?'),
        ),
    ]
