# Generated by Django 6.0 on 2026-03-17 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cameras', to=settings.AUTH_USER_MODEL, verbose_name='Владелец (Аккаунт)'),
        ),
        migrations.AddField(
            model_name='personface',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_faces', to=settings.AUTH_USER_MODEL, verbose_name='Владелец профиля'),
        ),
    ]
