# Generated by Django 6.0 on 2026-03-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_roles_and_companies(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    CustomUser = apps.get_model("accounts", "CustomUser")
    PersonFace = apps.get_model("accounts", "PersonFace")

    for user in CustomUser.objects.all():
        if user.is_superuser:
            role = "superadmin"
        elif user.is_camera:
            role = "camera"
        elif user.is_staff:
            role = "admin"
        else:
            role = "user"
        user.role = role
        user.save(update_fields=["role"])

    for admin_user in CustomUser.objects.filter(is_superuser=False, is_staff=True, company__isnull=True):
        company = Company.objects.create(name=f"{admin_user.username} Company")
        admin_user.company_id = company.id
        admin_user.save(update_fields=["company"])

    for user in CustomUser.objects.filter(company__isnull=True).exclude(owner__isnull=True):
        if user.owner and user.owner.company_id:
            user.company_id = user.owner.company_id
            user.save(update_fields=["company"])

    for face in PersonFace.objects.filter(company__isnull=True).exclude(owner__isnull=True):
        if face.owner and face.owner.company_id:
            face.company_id = face.owner.company_id
            face.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_owner_personface_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="users", to="accounts.company"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(choices=[("superadmin", "Super Admin"), ("admin", "Company Admin"), ("user", "User"), ("camera", "Camera")], default="user", max_length=20),
        ),
        migrations.AddField(
            model_name="personface",
            name="company",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="faces", to="accounts.company"),
        ),
        migrations.RunPython(populate_roles_and_companies, migrations.RunPython.noop),
    ]
